[package]
name = "http-client"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
bytes = "1"
chrono = "0.4"
pretty_env_logger = "0.4"
openssl = { version = "0.10", features = ["vendored"] }