[package]
edition = "2021"
name = "wasm-app"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
wasmedge_http_req = "0.9.0"