[package]
name = "run-wasm-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmedge-sdk = { version="0.7.1",features = ["async"]}
tokio = {version = "1.0", features = ["full"]}