[package]
name = "grpc-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tonic = "0.12.2"
prost = "0.13.2"

[build-dependencies]
tonic-build = "0.12.2"