[package]
name = "func_a_vanilla"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmedge_http_req = "0.9.0"
chrono = "0.4.24"
